### ISSUE TITLE
Support for Network drives

### ISSUE THREAD

**Issue by XenHat** [Eternita-S/JustBackup#1]
I would like to backup my configuration to my NAS using mounted network drives, but the plugin crashes when I try to do so:

```
15:10:35.602 | ERR [JustBackup] Error creating backup: Could not find a part of the path 'Z:\FFXIV\JustBackup'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at JustBackup.JustBackup.<>c__DisplayClass8_0.<DoBackup>b__0() in C:\VS\JustBackup\JustBackup\JustBackup.cs:line 104
   ```

Using a Samba path (i.e. `\\Server\folder\)` seems to work, at least sometimes:
<details>
<summary>Log of archive being created on SMB destination</summary>

```
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "7-Zip (r) 21.07 (x64) : Igor Pavlov : Public domain : 2021-12-26"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "Scanning the drive:"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "54 folders, 5031 files, 245188717 bytes (234 MiB)"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "Creating archive: \\ZARYA\xenhat\FFXIV\JustBackup\Backup-FFXIV-2022-04-27 15-14-32-5209707.7z"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "Add new data to archive: 54 folders, 5031 files, 245188717 bytes (234 MiB)"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "Files read from disk: 5031"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "Archive size: 13565615 bytes (13 MiB)"
--------------------------------
15:15:10.697 | DBG [System.Diagnostics.Process] 7-zip output: "Everything is Ok"
--------------------------------
15:15:10.698 | DBG [System.Diagnostics.Process] 7-zip output: null
--------------------------------
15:15:10.699 | INF [JustBackup] Backup complete.
```
</details>

**Comment by Eternita-S** [comment]
Hmm, this is strange, for me it works just fine every time with network mounted drive.
Can you check that:
- You are not running FFXIV as administrator
- Your network drive has connected status in windows explorer, like this:
![image](https://user-images.githubusercontent.com/5073202/165634365-e105bee6-5047-4922-ac64-6c7597d9b84a.png)
(and does not have red cross instead)
- Path to the destination folder actually exist?

**Comment by XenHat** [comment]
That is really strange. It failed yesterday after trying multiple times, but today it seems to be working fine. I wonder if my NAS hit a hiccup or something.. Closing for now as everything seems to be in order.

<details><summary>Log</summary>



```log
17:27:42.122 | INF [JustBackup] Backup path: \\ZARYA\xenhat\FFXIV\JustBackup
Temp folder: [censored]\AppData\Local\Temp\JustBackup-1651181262121
Ffxiv config folder: C:\NewLibraries\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn
Plugin config folder: [censored]\AppData\Roaming\XIVLauncher\pluginConfigs
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "7-Zip (r) 21.07 (x64) : Igor Pavlov : Public domain : 2021-12-26"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "Scanning the drive:"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "62 folders, 5117 files, 250163963 bytes (239 MiB)"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "Creating archive: \\ZARYA\xenhat\FFXIV\JustBackup\Backup-FFXIV-2022-04-28 17-26-59-0286627.7z"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "Add new data to archive: 62 folders, 5117 files, 250163963 bytes (239 MiB)"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "Files read from disk: 5117"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "Archive size: 13564621 bytes (13 MiB)"
--------------------------------
17:27:49.664 | DBG [System.Diagnostics.Process] 7-zip output: "Everything is Ok"
--------------------------------
17:27:49.665 | DBG [System.Diagnostics.Process] 7-zip output: null
--------------------------------
17:27:49.666 | INF [JustBackup] Backup complete.
--------------------------------
17:27:49.666 | DBG [JustBackup] Beginning auto-deletion of old backups
--------------------------------
17:27:49.670 | DBG [JustBackup] 6 backups found, 10 ordered to be kept, not deleting anything
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "7-Zip (r) 21.07 (x64) : Igor Pavlov : Public domain : 2021-12-26"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "Scanning the drive:"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "62 folders, 5117 files, 250163963 bytes (239 MiB)"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "Creating archive: \\ZARYA\xenhat\FFXIV\JustBackup\Backup-FFXIV-2022-04-28 17-27-46-7260285.7z"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "Add new data to archive: 62 folders, 5117 files, 250163963 bytes (239 MiB)"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "Files read from disk: 5117"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "Archive size: 13566932 bytes (13 MiB)"
--------------------------------
17:28:33.820 | DBG [System.Diagnostics.Process] 7-zip output: "Everything is Ok"
--------------------------------
17:28:33.821 | DBG [System.Diagnostics.Process] 7-zip output: null
--------------------------------
17:28:33.822 | INF [JustBackup] Backup complete.
--------------------------------
17:28:33.822 | DBG [JustBackup] Beginning auto-deletion of old backups
--------------------------------
17:28:33.824 | DBG [JustBackup] 6 backups found, 10 ordered to be kept, not deleting anything
--------------------------------
17:28:38.399 | INF [JustBackup] Backup path: Z:\FFXIV\JustBackup
Temp folder: [censored]\AppData\Local\Temp\JustBackup-1651181318399
Ffxiv config folder: C:\NewLibraries\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn
Plugin config folder: [censored]\AppData\Roaming\XIVLauncher\pluginConfigs
--------------------------------
17:29:05.297 | INF [JustBackup] Backup path: Z:\FFXIV\JustBackup
Temp folder: [censored]\AppData\Local\Temp\JustBackup-1651181345295
Ffxiv config folder: C:\NewLibraries\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn
Plugin config folder: [censored]\AppData\Roaming\XIVLauncher\pluginConfigs
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "7-Zip (r) 21.07 (x64) : Igor Pavlov : Public domain : 2021-12-26"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "Scanning the drive:"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "62 folders, 5117 files, 250163963 bytes (239 MiB)"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "Creating archive: Z:\FFXIV\JustBackup\Backup-FFXIV-2022-04-28 17-28-42-6839483.7z"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "Add new data to archive: 62 folders, 5117 files, 250163963 bytes (239 MiB)"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: ""
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "Files read from disk: 5117"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "Archive size: 13566296 bytes (13 MiB)"
--------------------------------
17:29:32.827 | DBG [System.Diagnostics.Process] 7-zip output: "Everything is Ok"
--------------------------------
17:29:32.829 | DBG [System.Diagnostics.Process] 7-zip output: null
--------------------------------
17:29:32.829 | INF [JustBackup] Backup complete.
--------------------------------
17:29:32.829 | DBG [JustBackup] Beginning auto-deletion of old backups
--------------------------------
17:29:32.831 | DBG [JustBackup] 8 backups found, 10 ordered to be kept, not deleting anything
```
