### ISSUE TITLE
[Feature Request] Ignore folders for Chrome based plugins

### ISSUE THREAD

**Issue by thakyZ** [Eternita-S/JustBackup#14]
Plugins such as Browsingway use chrome to render web elements on the plugin window. This plugin tries to backup the folder   
`cef-cache` which is located in the `Browsingway` folder in the `pluginConfigs` folder.

I would like to suggest to ignore folders called `cef-cache` and plainly called `cef` as Browsingway also has a `dependencies` folder that contains `cef`. That should greatly reduce any size of the backups.

On top of not outputting errors like this:
```csharp
2023-03-27 10:01:06.284 -07:00 [ERR] [JustBackup] Error copying file E:\FFXIV\XIVLauncher\pluginConfigs\Browsingway\cef-cache\LOCK to C:\Users\thaky\AppData\Local\Temp\JustBackup-1679936465908\plugins\Browsingway\cef-cache: The process cannot access the file because another process has locked a portion of the file. : 'E:\FFXIV\XIVLauncher\pluginConfigs\Browsingway\cef-cache\LOCK'
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at JustBackup.JustBackup.CopyFile(String file, String dest) in /work/repo/JustBackup/JustBackup.cs:line 280
```

**Comment by Limiana** [comment]
uh oh, I totally didn't expect chrome in plugin configs folder
will be added (you can already exclude by adding path manually in testing version also)

**Comment by Limiana** [comment]
This feature was implemented in one of previous versions
