### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by kumail-r** [Eternita-S/JustBackup#4]
Is there any chance of adding Linux (proton) support?

**Comment by Eternita-S** [comment]
Hello.
Could you tell me what is not working on Linux right now?
Ideally, also attach `%appdata%\XIVLauncher\dalamud.log` file (after booting the game with JustBackup installed)

**Comment by NononaNona** [comment]
I believe the issue is that the game config and plugin config folders are in different locations. I couldn't find an option to directly change those locations, but I think adding this to the configuration should fix this.

Example dalamud.log:
`2022-08-10 16:29:15.603 -05:00 [ERR] [JustBackup] Error creating backup: Could not find a part of the path 'C:\users\nona\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all) in C:\VS\JustBackup\JustBackup\JustBackup.cs:line 244
   at JustBackup.JustBackup.<>c__DisplayClass9_0.<DoBackup>b__0() in C:\VS\JustBackup\JustBackup\JustBackup.cs:line 99
2022-08-10 16:29:16.044 -05:00 [ERR] [JustBackup] Error deleting temp files: Could not find a part of the path 'C:\users\nona\Temp\JustBackup-1660166954056'.
   at System.IO.FileSystem.GetFindData(String fullPath, WIN32_FIND_DATA& findData)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at JustBackup.JustBackup.<>c__DisplayClass9_0.<DoBackup>b__0() in C:\VS\JustBackup\JustBackup\JustBackup.cs:line 217`

**Comment by Eternita-S** [comment]
hmm, thanks, I'll try to take a look on it soon

**Comment by AamuLumi** [comment]
Hello !

I tested and reproduced this bug on my Steamdeck (configuration with Proton 7).
The ideal fix would be to just **add a text field for the FFXIV configuration folder path**.
On my device, the configuration path is `~/.xlcore/ffxivConfig`, but the game is running with Proton, so the path will be something like `Z:\home\deck\.xlcore\ffxivConfig`.

If you want a temporary fix, you can create a symbolic link to the config folder in your Documents folder, which is mounted in Proton.

In my case, I did this : 
```
cd ./Documents
mkdir "My Games"
ln -s ~/.xlcore/ffxivConfig "./My Games/FINAL FANTASY XIV - A Realm Reborn"
```
After that, Proton was able to find my configuration and backup it correctly.

Oh and I use a custom path for backup folder.

Maybe I'll propose a PR if I'm able to setup the project to fix that.

**Comment by Limiana** [comment]
Apologies, I've been busy. I'm going to make update as soon as I can

**Comment by mnn** [comment]
On my old PC it worked with XIVLauncher (via Lutris, everything via Wine - the launcher and the game), but on new PC I am using the native XLCore (the launcher runs natively and the game via bundled wine/proton; I believe this is the recommended way how to run the game on Linux) and the plugin crashes on game start:

```
06:31:39.256 | ERR [JustBackup] Error creating backup: Could not find a part of the path 'C:\users\xxx\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all) in /work/repo/JustBackup/JustBackup.cs:line 247
   at JustBackup.JustBackup.<>c__DisplayClass9_0.<DoBackup>b__0() in /work/repo/JustBackup/JustBackup.cs:line 104
06:31:39.256 | VRB [GameFontManager] AfterBuildFonts: Scaling "GameFontStyle(Jupiter23, 23pt, skew=0, weight=0)" from 23pt to 23pt (scale: 1)
06:31:39.258 | VRB [GameFontManager] AfterBuildFonts: Scaling "GameFontStyle(Axis12, 12pt, skew=0, weight=0)" from 12pt to 12pt (scale: 1)
06:31:39.258 | DBG [SimpleTweaksPlugin] Initalizing Tweak: AutoLockHotbar
06:31:39.260 | ERR [JustBackup] Error deleting temp files: Could not find a part of the path 'C:\users\xxx\Temp\JustBackup-1685248299206'.
   at System.IO.FileSystem.GetFindData(String fullPath, Boolean isDirectory, Boolean ignoreAccessDenied, WIN32_FIND_DATA& findData)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at JustBackup.JustBackup.<>c__DisplayClass9_0.<DoBackup>b__0() in /work/repo/JustBackup/JustBackup.cs:line 222
```

---

> Is there any chance of adding Linux (proton) support?

Just a nitpick, but technically it supports "Linux (proton)", it doesn't support XLCore - a way with "less Proton".
